name = "rate-limiter-worker"
main = "index.js"
compatibility_date = "2025-06-25"

# KV namespaces for dynamic rate limiting (FREE tier - 100k reads/day, 1k writes/day)
[[kv_namespaces]]
binding = "FAQ_RATE_LIMITS"
id = "77fcd59503e34efcaf4d77d1a550433b"  # Main rate limiting data
# preview_id = "YOUR_PREVIEW_ID_HERE"  # Optional - only needed for wrangler dev --local=false

[[kv_namespaces]]
binding = "FAQ_IP_WHITELIST"
id = "77fcd59503e34efcaf4d77d1a550433b"  # IP whitelist (can use same namespace)
# preview_id = "YOUR_PREVIEW_ID_HERE"

[[kv_namespaces]]
binding = "FAQ_IP_BLACKLIST"
id = "77fcd59503e34efcaf4d77d1a550433b"  # IP blacklist (can use same namespace)
# preview_id = "YOUR_PREVIEW_ID_HERE"

[[kv_namespaces]]
binding = "FAQ_VIOLATIONS"
id = "77fcd59503e34efcaf4d77d1a550433b"  # Violation tracking (can use same namespace)
# preview_id = "YOUR_PREVIEW_ID_HERE"

[[kv_namespaces]]
binding = "FAQ_ANALYTICS"
id = "77fcd59503e34efcaf4d77d1a550433b"  # Analytics data (can use same namespace)
# preview_id = "YOUR_PREVIEW_ID_HERE"

# Development settings
[dev]
port = 8787
local_protocol = "http"
# ip = "0.0.0.0"  # Uncomment if you need to access from other devices on your network

# Performance limits (staying within FREE tier)
[limits]
cpu_ms = 10  # Free tier limit: 10ms CPU time per request

# Environment variables (optional)
[vars]
# Add any environment variables here if needed
# ENVIRONMENT = "production"

# Routes - ONLY uncomment if you have a domain on Cloudflare
# [routes]
# pattern = "rate-limiter.example.com/*"
# zone_name = "example.com"

# OR use workers.dev subdomain (FREE)
# workers_dev = true  # This is default anyway

# Compatibility flags (optional)
# [compatibility_flags]
# nodejs_compat = true  # If you need Node.js APIs

# Build configuration (if using build step)
# [build]
# command = "npm run build"
# watch_paths = ["src/**/*.js"]

# Observability (optional - some features require paid plan)
# [observability]
# enabled = true

# Triggers (none needed for this worker)
# [triggers]
# crons = []

# Analytics (optional - requires paid plan)
# [analytics_engine_datasets]
# RATE_LIMITER_ANALYTICS = "rate_limiter_analytics"

################################################################################
# DELETED SECTIONS - DO NOT ADD THESE BACK (they cost money!)
################################################################################
# 
# [[durable_objects.bindings]]  # ❌ REMOVED - Durable Objects cost money!
# name = "RATE_LIMITER_DO"
# class_name = "RateLimiterDO"
#
# [[migrations]]  # ❌ REMOVED - No Durable Objects = No migrations needed
# tag = "v2" 
# new_classes = ["RateLimiterDO"]
#
# [durable_objects]  # ❌ REMOVED - No Durable Objects configuration
# alarms = true
#
################################################################################

# That's it! This configuration will keep you on the FREE tier! 🎉